### ISSUE TITLE
[Suggestion] Allow coloring and labelling of buttons

### ISSUE THREAD

**Issue by robbi-blechdose** [tommy1019/Totality#1]
It'd be nice to be able to set colors and short labels for buttons, to make them easier to recognize to the user.

**Comment by tommy1019** [comment]
You can already add text to a controller, we will add coloring of buttons and joysticks to the next version of Totality

**Comment by tommy1019** [comment]
Added in 29ea5eaa97dcc71052e10c62faef073edaa28ad3
