### ISSUE TITLE
Gradle / Maven support

### ISSUE THREAD

**Issue by quexten** [tommy1019/Totality#3]
Gradle / Maven support would make adding this library much easier since Gson could be declared as a dependency and you wouldn't have to put jars (binaries) into your project, and adding totality would be just 1 line in your build script. Additionally, the most popular java gaming framework (libgdx) comes with gradle as the build chain of choice i recommend adding gradle build support.

**Comment by gcmvy3** [comment]
Hi - thanks for trying Totality!
You're right, we should have support for this. I'll get working on it.

**Comment by tommy1019** [comment]
Planned for version 1.1.0

**Comment by tommy1019** [comment]
Added in version 1.1.0
