### ISSUE TITLE
Clean shutdown

### ISSUE THREAD

**Issue by robbi-blechdose** [tommy1019/Totality#5]
Sorry for reporting so many issues,
but it seems that Totality does not shutdown cleanly.
When running my game from Netbeans, the console shows it never stops when I close the window. Without totality, I get the "BUILD SUCCESSFUL" message almost immediately.
Maybe it's possible to add a "stop()" method to Totality?

**Comment by gcmvy3** [comment]
Thanks for posting issues, it helps us make Totality better. 

This is kind of an odd one. In all of our tests, Totality shuts down when the program closes. It could be a quirk with NetBeans or maybe a library you're using.

We're looking into it, but we'll add a stop() method in case other people have this problem.

**Comment by tommy1019** [comment]
Fixed in 1.1.0 - 9a14a2e
